name: CI
on:
    push:
        branches: [ master ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: ninja
              run: sudo apt update -y && sudo apt install -y ninja-build cmake
            - name: 01_2_mkdir
              run: mkdir 01_2/build
            - name: 01_2_build
              run: cmake -G Ninja -S 01_2 -B 01_2/build

